<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e8019c16-b2e0-4972-aa6b-fae3a3195804</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StokTakip.Application\StokTakip.Application.csproj" />
    <ProjectReference Include="..\StokTakip.Infrastructure\StokTakip.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.*" />
  </ItemGroup>
</Project>
